sudo: required
language: bash
env:
  global:
  - LIVE_SERVICE=deployment
  - LIVE_CLUSTER_NAME=travis
  - LIVE_APP_NAME=travis
  - AWS_URL=729312012182.dkr.ecr.ap-southeast-1.amazonaws.com
  - secure: J09IDL8TL4LNivPMvsB33BYccwIjIM3zbX5J4K5kN28L+6OVP5NTr0XJLbVlFe5NcDbPUZQ75YuX2qKI0EtMcbNieD4YdUw8v5I31piPTLMMvBbfnLz4wfNji6HqLXTLddKk6FTg5vHziGArd2zzRXGm1RbD4hqSej/Oj9NodOjYJxjMPBtfIia99cv73gIkf9vCk8plPY56bbrgTMMW25FcCuD4h8lTZpfWcajHKNO0rLhzBjJu37aPtk0eUINXfA57bpyfBVRTzQKbgV1OXq78I91ThzUJhm0zUBN/Age5w1u57h80wxnEiIGdAv0eJ/BjV+aMtVfxvEYPWvmzx6ZtjowODYmuZSp10i4/A4OBqNkEePR4f9UYg2MVzVkSywR04gp7ZfMGhpHfFesbrF2D1gfz7onbuP5zxgWTm/gXhtO+yx9jQoLnKSuODdt4XayAgS8eo0q7sLfn+VlMr67yQdfaEgltg5lNf8Lv/w/VjpSEWR5cZwuxj63DAmq/lOLTGIi9hAPWE5sui4fU04W6KZX941uX6QCqVxdKAhfcFxiE1SnUprTU6/DhyWTu+RovHR/wU5T3Vo56jyT1k9S64W4/lSgiD7I0DzSmeKbeXCdPB4orLEy2jtA2VjzdfGOgr0bCXBmIotukMzGdo+f8tbb+0k1LgxozQls9naY=
  - secure: isRc28N9V3/uZazyLRDWkXjMK+4ju/e9B2TlmrqLx5OtqbY2qOlkP1tBWyuNnAE0kiVesOZOEDLRBIUID4FH5lyaj7FeJ6VESo4eW+M/mtoUqLlfnnXKjohBqsErKt1EyunXriA9AFtjdZPBna+COaL3Of199/f0hxa27KyzwfhXMSJTy4EAFvbIQ35ZtdQheNGnGfvwH5c+7Bxn2cshZcKbQJL9rKaxFb3jvX8LQyIKMMfbozs7YbdrDy9dV4ZduV9VbVeTfJ5hAcMsbNBjTSXkrmeHi/ZV1olQiovehPyohNNG+Fvq3AGGd7rdvMb60q3XuRRF5yQ5ZNNmvhtYUAWOGKaK/jLcNcKMtORSJ5+ZXgOkPMFCeDc9xemm+c30ij2XEY66ii4fZUyvI5uvPmGWoSjfRogAzmcyxTB5nrnd0Sqwz7ak8GPDz2BAQgR9BdM76OXQgRmTpQCoQs1EAztEFqRCW6Os4gzfPOjddSUJ3JVRiyqMjsvvLctYo99iTbAvRfgGz2SS1hS52zwP9ZIQPg9tnU8AGJMRWxRE8TFKib/IJgdOJSUwxLEBnpSz2v/NnFuqnp2aUXKXaWvgznFHd9WprTCzhM436MvHTgatO6mrk6G+lnMHG9QX9ZPekEq5QIL5w8IOCSIWPErRfm4tHYaENoxUvzp7KXyXAg0=
services:
- docker
script:
- echo "No tests!"
after_success:
- docker-deploy/docker_push.sh
- docker-deploy/ecs_deploy.sh
